### ISSUE TITLE
竖屏视频问题

### ISSUE THREAD

**Issue by jiangkaifang** [lakehubo/HBanner#16]
作者您好，收先感谢您的分享，在使用的时候发现了两个小问题在这里反馈一下

1. 从1.0.1版本开始（1.0.0不存在这个问题），竖屏视频默认显示在中间了，但是如果是一个竖屏视频和一个图片轮播的话，显示图片的时候会显示一秒就黑屏了，等图片显示时间到的前一秒又会显示一下然后就切换到视频了。
  不知道有没有描述清楚，总之重现方式是：加载一个竖屏视频和任意一个图片，视频切换到图片时就会出现这个问题；

2. 此问题在1.0.3版本确认存在，之后的版本未测试。问题描述：
加载媒体越多越容易出现，比如加载了10个视频和10个图片，然后再即将要切换下一个元素时立即（不需要那么及时，大概切换的前后就行）触发更新动作（就是调用hBanner.update方法），如果更新后的内容比之前的少，比如只剩下一个视频和一个图片，会引起崩溃。我把HB'anner类复制下来做了个修改解决了此问题，但具体修改的哪我真的想不起来了，好像是因为lastItem的问题，我在update方法里设置了lastItem=0;（不确定，真记不清了）

--------------------------------------------------------------
再次感谢作者的分享

**Comment by DiaosiDev** [comment]
这个问题作者可以修复么

**Comment by DiaosiDev** [comment]
这个问题解决了 viewpager 加载竖屏视频是 在remove子view后子view还是会重复测绘  导致后面的图片不能正常加载  在CustomVideoView使用的时候增加一层ViewGroup嵌套 限制子view移除后的测绘

**Comment by lakehubo** [comment]
最新1.0.8已解决上述问题
