### ISSUE TITLE
手动滚动图片后，播放被暂停

### ISSUE THREAD

**Issue by wesley235** [lakehubo/HBanner#43]
手动滚动图片后，播放被暂停。当下一张为图片时，无法自动播放，下一张为视频时，可以自动播放

**Comment by lakehubo** [comment]
当前为视频时，手动滑动，视频还未结束，会导致轮播停止，是因为视频直接被stop没有执行shownext。这里的逻辑问题我还没有解决。

**Comment by lakehubo** [comment]
目前滑动无法自动播放的bug已修复
