### ISSUE TITLE
注意点HBannerImp第100行addOnPageChangeListener的调用者是外部实例化的View在所以存在多次监听的情况，导致滚动位置错乱

### ISSUE THREAD

**Issue by carsher** [lakehubo/HBanner#49]
//查看androidx.viewpager.widget.ViewPager 源码addOnPageChangeListener内维护的是一个List
  public void addOnPageChangeListener(@NonNull OnPageChangeListener listener) {
        if (mOnPageChangeListeners == null) {
            mOnPageChangeListeners = new ArrayList<>();
        }
        mOnPageChangeListeners.add(listener);
    }
//HBannerImp第100行，作者的使用方式这里存在漏洞，具体场景需要多次create()
解决方式：最简单的方式在androidx.viewpager.widget.PagerAdapter#instantiateItem作如下修改：
      @NonNull
        @Override
        public Object instantiateItem(@NonNull ViewGroup container, int position) {
            View view = usingItems.get(position);
            ViewGroup parent = (ViewGroup) view.getParent();
            if (parent != null){
                parent.removeView(view);
            }
            container.addView(view);
            return view;
        }
在不修改源码情况下在create前可使用：
               viewPager.removeAllViews();
               viewPager.clearOnPageChangeListeners();

**Comment by lakehubo** [comment]
目前已提供release释放方法
